name    'dblessing-puppet_omnibus_gem'
version '0.0.1'
source  'https://github.com/dblessing/dblessing-puppet_omnibus_gem'
author  'Drew Blessing'
license 'Apache License 2.0'
summary 'Puppet Omnibus Gem Module'
description 'Install gems in Puppet Omnibus environment'
project_page 'https://github.com/dblessing/dblessing-puppet_omnibus_gem'
